# -*- coding: utf-8 -*-
"""treinamento_YOLOv4_hripcb.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/10LcoOmSDQbwCXTL0Vd0twqukQaZAzJzM
"""
import cv2
import matplotlib.pyplot as plt
import tensorflow as tf

!git clone https://github.com/AlexeyAB/darknet
!git clone https://github.com/Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB

%cd darknet

!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile #habilitar treinamento em GPU
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile
!make

#incluir arquivos de treinamento para a pasta darknet
!cp -R /content/pcb_data/obj /content/darknet/data
!cp -R /content/pcb_data/valid /content/darknet/data
#incluir arquivos de configurações para a pasta darknet
!cp /content/yolov4/cfg/obj.data /content/darknet/data
!cp /content/yolov4/cfg/obj.names /content/darknet/data
!cp /content/yolov4/cfg/yolov4_custom.cfg /content/darknet/cfg
!cp /content/yolov4/train.txt /content/darknet/data
!cp /content/yolov4/test.txt /content/darknet/data

#transferencia de aprendizagem
!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.conv.137
#treinamento
!./darknet detector train data/obj.data cfg/yolov4_custom.cfg yolov4.conv.137 -dont_show -map
